# Generated by Django 5.2.5 on 2025-08-23 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0001_initial"),
        ("projectapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article",
                to="projectapp.project",
            ),
        ),
    ]
